service: rest-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript 
  - serverless-offline


functions:
  getAllMenu:
    handler: app/handler.getAllMenu
    events:
      - http:
          path: /api/v1/menu
          method: get

  createMenu:
    handler: app/handler.createMenu
    events:
      - http:
          path: /api/v1/menu
          method: post
  
  deleteMenu:
    handler: app/handler.deleteMenu
    events:
      - http:
          path: /api/v1/menu/{id}
          method: delete
